### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by raivivek** [kauralasoo/txrevise#2]
Hi @kauralasoo, I'm wondering if authors could create a tagged GitHub release? This will make it easier to reference the package and specific version of it in places such as Bioconda.

I'm trying to create a package which will make it easy to install txrevise through conda.

https://github.com/bioconda/bioconda-recipes/pull/20481

**Comment by kauralasoo** [comment]
Hi @raivivek,
Yes, that's a very good point! I created a first release - https://github.com/kauralasoo/txrevise/releases/tag/v0.1. Let me know if there's anything else that I can do.

**Comment by raivivek** [comment]
Thanks! This should work. You can follow along the progress on the recipe if you wish. I'll get back to you if I need more help! :)

**Comment by raivivek** [comment]
@kauralasoo The recipe is now merged and should be available in bioconda. :-)
